[versions]
# libraries
annotations = "24.0.1"
ivy = "2.5.2"
httpclient = "4.5.13"
oro = "2.0.8"
vfs2 = "2.2"
jsch = "0.1.55"
jschAgentproxy = "0.0.9"
bouncycastle = "1.70"

# plugins
changelog = "2.2.1"
intelliJPlatform = "2.0.1"
kotlin = "1.9.25"
kover = "0.8.3"
qodana = "2024.1.9"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
ivy = { group = "org.apache.ivy", name = "ivy", version.ref = "ivy" }
httpclient = { group = "org.apache.httpcomponents", name = "httpclient", version.ref = "httpclient" }
oro = { group = "oro", name = "oro", version.ref = "oro" }
vfs2 = { group = "org.apache.commons", name = "commons-vfs2", version.ref = "vfs2" }
jsch = { group = "com.jcraft", name = "jsch", version.ref = "jsch" }
jschagentproxyconnectorfactory = { group = "com.jcraft", name = "jsch.agentproxy.connector-factory", version.ref = "jschAgentproxy" }
jschagentproxyjsch = { group = "com.jcraft", name = "jsch.agentproxy.jsch", version.ref = "jschAgentproxy" }
bcpg = { group = "org.bouncycastle", name = "bcpg-jdk15on", version.ref = "bouncycastle" }
bcprov = { group = "org.bouncycastle", name = "bcprov-jdk15on", version.ref = "bouncycastle" }
junit = { group = "junit", name = "junit", version = "4.12" }
assertj = { group = "org.assertj", name = "assertj-core", version = "3.15.0" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }